### ISSUE TITLE
Strings beginning with "True" or ending with "False" rendered as TRUE/FALSE

### ISSUE THREAD

**Issue by rcook** [seamusabshere/xlsx_writer#13]
Minimal reproducer:

```ruby
require 'fileutils'
require 'xlsx_writer'

workbook = XlsxWriter.new
worksheet = workbook.add_sheet('Foo')
worksheet.add_row(['Frederick', 'Sewards', 'Trueman'])
FileUtils.mv workbook.path, 'foo.xlsx'
workbook.cleanup
```

This results in a worksheet with three cells with values "Frederick" (type string), "Sewards" (type string) and FALSE (boolean value). `xlsx_writer` looks like it is erroneously coercing these strings as booleans.

Update: The bug is in the `TRUE_FALSE_PATTERN` regular expression in the `XlsxWriter::Cell` class. Instead of:

```ruby
TRUE_FALSE_PATTERN = %r{^true|false$}i
```

it should read

```ruby
TRUE_FALSE_PATTERN = %r{^true$|^false$}i
```

i.e. The `^` and `$` anchors should be repeated around both `true` and `false` due to the precedence of the `|` operator.

I'll prepare a pull request with the fix.

**Comment by JacobEvelyn** [comment]
Is there any chance of this merging? This is definitely an issue for us.

Additionally, is there a way to *not* coerce "true" and "false" cells explicitly rendered with type `:String` to booleans?

**Comment by rcook** [comment]
I've submitted a pull request from https://github.com/rcook/xlsx_writer.

**Comment by JacobEvelyn** [comment]
Sadly, this repo appears to be unmaintained. :(

Any updates, @seamusabshere?

**Comment by rcook** [comment]
@JacobEvelyn : Feel free to use my fork at https://github.com/rcook/xlsx_writer if that's useful to you.

**Comment by JacobEvelyn** [comment]
Thanks! Pointing my gemfile at it now :)
